"""empty message

Revision ID: 3afb55798b8d
Revises: 
Create Date: 2022-03-17 01:37:24.351368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afb55798b8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etapas', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datos_baby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.Column('estatura', sa.String(length=50), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapas',
    sa.Column('actividades_id', sa.Integer(), nullable=False),
    sa.Column('datos_baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividades_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['datos_baby_id'], ['datos_baby.id'], ),
    sa.PrimaryKeyConstraint('actividades_id', 'datos_baby_id')
    )
    op.create_table('logros_bebes',
    sa.Column('actividades_id', sa.Integer(), nullable=False),
    sa.Column('datos_baby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividades_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['datos_baby_id'], ['datos_baby.id'], ),
    sa.PrimaryKeyConstraint('actividades_id', 'datos_baby_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logros_bebes')
    op.drop_table('etapas')
    op.drop_table('profiles')
    op.drop_table('datos_baby')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('actividades')
    # ### end Alembic commands ###
